# load("@rules_go//go:def.bzl", "go_binary","go_library")
#
# go_library(
#     name = "hbase_client_lib",
#     srcs = [
#         "main.go",
#     ],
#     visibility = ["//visibility:public"],
#     deps = [
#         "@com_github_tsuna_gohbase//:go_default_library",
#          "@gohbase//pb:pb_go_proto",
#     ]
# )
#
# go_binary(
#     name = "hbase_client",
#     embed = [":hbase_client_lib"],
# )