load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "ws",
    srcs = ["ws.go"],
    importpath = "com.tm.go/lib/model/ws_model",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_gorilla_websocket//:go_default_library",
    ]
)
