load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "annotation",
    srcs = glob(["*.java"]),
    deps = [
        "//plugins:dagger",
    ],
    visibility = ["//visibility:public"],
)