load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "interview",
    main_class = "com.tm.java.interview.Main",
    srcs = glob(["*.java"]),
    runtime_deps = [],
)
